### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 500
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 111
}


### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "480d1ea768bf4ccd95d1a95d02af26f1",
  "accountNumber": "1000000001",
  "amount": 500
}

### query transaction
GET http://localhost:8080/transaction/70c814a5c7f143dfab02e2245e1b3002
