### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 2,
  "accountNumber": "1000000003",
  "amount": 1000000000000000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 111
}


### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "322074d13df6470ba21529f950fede79",
  "accountNumber": "1000000004",
  "amount": 500
}

### query transaction
GET http://localhost:8080/transaction/322074d13df6470ba21529f950fede79
